using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace BDOServerRatesEditor
{
  public class Networks : Form
  {
    private string _conf1 = Directory.GetCurrentDirectory() + "\\gameserver\\bin\\configs\\network.properties";
    private string _conf2 = Directory.GetCurrentDirectory() + "\\loginserver\\bin\\configs\\network.properties";
    private string _conf3 = Directory.GetCurrentDirectory() + "\\gameserver\\bin\\configs\\server.properties";
    private IContainer components = (IContainer) null;
    public static string SearchKey1;
    public static string SearchKey2;
    public static string SearchKey3;
    public static string SearchKey4;
    public static string SearchKey5;
    public static string SearchKey6;
    public static string SearchKey7;
    public static string SearchKey8;
    public static string SearchKey9;
    public static string SearchKey10;
    public static string SearchKey11;
    public static string SearchKey12;
    public static string SearchKey13;
    public static string SearchKey14;
    public static string SearchKey15;
    public static string SearchKey16;
    public static string SearchKey17;
    public static string SearchKey18;
    public static string SearchKey19;
    public static string SearchKey20;
    private Button button1;
    private TextBox textBox1;
    private TextBox textBox2;
    private TextBox textBox3;
    private TextBox textBox4;
    private TextBox textBox5;
    private TextBox textBox6;
    private TextBox textBox7;
    private TextBox textBox8;
    private TextBox textBox9;
    private TextBox textBox10;
    private TextBox textBox11;
    private TextBox textBox12;
    private Label label1;
    private Label label2;
    private Label label3;
    private Label label4;
    private Label label5;
    private Label label6;
    private Label label7;
    private Label label8;
    private Label label9;
    private Label label10;
    private Label label11;
    private Label label12;
    private GroupBox groupBox1;
    private Label label13;
    private TextBox textBox13;
    private TextBox textBox14;
    private TextBox textBox15;
    private TextBox textBox16;
    private TextBox textBox17;
    private TextBox textBox18;
    private TextBox textBox19;
    private TextBox textBox20;
    private TextBox textBox21;
    private TextBox textBox22;
    private TextBox textBox23;
    private TextBox textBox24;
    private TextBox textBox25;
    private TextBox textBox26;
    private TextBox textBox27;
    private TextBox textBox28;
    private TextBox textBox29;
    private TextBox textBox30;
    private TextBox textBox31;
    private TextBox textBox32;
    private Label label14;
    private Label label15;
    private Label label16;
    private Label label17;
    private Label label18;
    private Label label19;
    private Label label20;
    private Label label21;
    private Label label22;
    private Label label23;
    private Label label24;
    private Label label25;
    private Label label26;
    private Label label27;
    private Label label28;
    private Label label29;
    private Label label30;
    private Label label31;
    private Label label32;
    private Label label33;
    private GroupBox groupBox2;

    public Networks()
    {
      this.InitializeComponent();
      this.Name = "Simple BDO Server Config";
      this.Text = "Simple BDO Server Config";
      bool flag1 = File.Exists(this._conf1);
      bool flag2 = File.Exists(this._conf2);
      bool flag3 = File.Exists(this._conf3);
      if (!flag1 || !flag2 || !flag3)
      {
        int num = (int) MessageBox.Show("Извините, файлы конфигурации отсутствуют! Вы уверены, что скопировали этот exe-файл в корневой каталог вашего сервера?", "Важные файлы отсутствуют!");
        Environment.Exit(0);
      }
      this.FillServerIni();
      this.FillNetworkIni();
    }

    public void FillServerIni()
    {
      string IniFileName = Directory.GetCurrentDirectory() + "\\gameserver\\bin\\configs\\server.properties";
      Networks.SearchKey1 = "server.id ";
      Networks.SearchKey2 = "server.short.name ";
      Networks.SearchKey3 = "server.channel.id ";
      Networks.SearchKey4 = "server.ip ";
      Networks.SearchKey5 = "server.game.service.type ";
      Networks.SearchKey6 = "server.game.resource.type ";
      Networks.SearchKey7 = "server.enable_pc_cafe_bonus ";
      Networks.SearchKey8 = "server.busy_state_limit_inspection ";
      Networks.SearchKey9 = "server.busy_state_limit_smooth ";
      Networks.SearchKey10 = "server.busy_state_limit_busy ";
      Networks.SearchKey11 = "server.busy_state_limit_very_crowded ";
      Networks.SearchKey12 = "server.admin_only ";
      string iniProperty1 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey1);
      string iniProperty2 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey2);
      string iniProperty3 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey3);
      string iniProperty4 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey4);
      string iniProperty5 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey5);
      string iniProperty6 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey6);
      string iniProperty7 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey7);
      string iniProperty8 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey8);
      string iniProperty9 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey9);
      string iniProperty10 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey10);
      string iniProperty11 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey11);
      string iniProperty12 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey12);
      if (iniProperty1 != null)
        this.textBox1.Text = iniProperty1;
      if (iniProperty2 != null)
        this.textBox2.Text = iniProperty2;
      if (iniProperty3 != null)
        this.textBox3.Text = iniProperty3;
      if (iniProperty4 != null)
        this.textBox4.Text = iniProperty4;
      if (iniProperty5 != null)
        this.textBox5.Text = iniProperty5;
      if (iniProperty6 != null)
        this.textBox6.Text = iniProperty6;
      if (iniProperty7 != null)
        this.textBox7.Text = iniProperty7;
      if (iniProperty8 != null)
        this.textBox8.Text = iniProperty8;
      if (iniProperty9 != null)
        this.textBox9.Text = iniProperty9;
      if (iniProperty10 != null)
        this.textBox10.Text = iniProperty10;
      if (iniProperty11 != null)
        this.textBox11.Text = iniProperty11;
      if (iniProperty12 == null)
        return;
      this.textBox12.Text = iniProperty12;
    }

    public void FillNetworkIni()
    {
      string currentDirectory = Directory.GetCurrentDirectory();
      string IniFileName = currentDirectory + "\\gameserver\\bin\\configs\\network.properties";
      string str = currentDirectory + "\\loginserver\\bin\\configs\\network.properties";
      Networks.SearchKey1 = "network.rmi.host ";
      Networks.SearchKey2 = "network.rmi.port ";
      Networks.SearchKey3 = "network.rmi.password ";
      Networks.SearchKey4 = "network.server.version ";
      Networks.SearchKey5 = "network.encrypt.packets ";
      Networks.SearchKey6 = "network.host ";
      Networks.SearchKey7 = "network.port ";
      Networks.SearchKey8 = "network.debug ";
      Networks.SearchKey9 = "network.packet.exec.mode ";
      Networks.SearchKey10 = "network.recv.buffer.size ";
      Networks.SearchKey11 = "network.send.buffer.size ";
      Networks.SearchKey12 = "network.server.socket.backlog ";
      Networks.SearchKey13 = "network.client.socket.options ";
      Networks.SearchKey14 = "network.server.socket.options ";
      Networks.SearchKey15 = "network.io.execution.mode ";
      Networks.SearchKey16 = "network.io.execution.thread.num ";
      Networks.SearchKey17 = "network.income.packet.header.size ";
      Networks.SearchKey18 = "network.max.income.packet.size ";
      Networks.SearchKey19 = "network.outcome.packet.header.size ";
      Networks.SearchKey20 = "network.max.outcome.packet.size ";
      string iniProperty1 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey1);
      string iniProperty2 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey2);
      string iniProperty3 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey3);
      string iniProperty4 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey4);
      string iniProperty5 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey5);
      string iniProperty6 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey6);
      string iniProperty7 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey7);
      string iniProperty8 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey8);
      string iniProperty9 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey9);
      string iniProperty10 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey10);
      string iniProperty11 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey11);
      string iniProperty12 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey12);
      string iniProperty13 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey13);
      string iniProperty14 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey14);
      string iniProperty15 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey15);
      string iniProperty16 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey16);
      string iniProperty17 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey17);
      string iniProperty18 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey18);
      string iniProperty19 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey19);
      string iniProperty20 = IniFile.GetIniProperty(IniFileName, Networks.SearchKey20);
      if (iniProperty1 != null)
        this.textBox13.Text = iniProperty1;
      if (iniProperty2 != null)
        this.textBox14.Text = iniProperty2;
      if (iniProperty3 != null)
        this.textBox15.Text = iniProperty3;
      if (iniProperty4 != null)
        this.textBox16.Text = iniProperty4;
      if (iniProperty5 != null)
        this.textBox17.Text = iniProperty5;
      if (iniProperty6 != null)
        this.textBox18.Text = iniProperty6;
      if (iniProperty7 != null)
        this.textBox19.Text = iniProperty7;
      if (iniProperty8 != null)
        this.textBox20.Text = iniProperty8;
      if (iniProperty9 != null)
        this.textBox21.Text = iniProperty9;
      if (iniProperty10 != null)
        this.textBox22.Text = iniProperty10;
      if (iniProperty11 != null)
        this.textBox23.Text = iniProperty11;
      if (iniProperty12 != null)
        this.textBox24.Text = iniProperty12;
      if (iniProperty13 != null)
        this.textBox25.Text = iniProperty13;
      if (iniProperty14 != null)
        this.textBox26.Text = iniProperty14;
      if (iniProperty15 != null)
        this.textBox27.Text = iniProperty15;
      if (iniProperty16 != null)
        this.textBox28.Text = iniProperty16;
      if (iniProperty17 != null)
        this.textBox29.Text = iniProperty17;
      if (iniProperty18 != null)
        this.textBox30.Text = iniProperty18;
      if (iniProperty19 != null)
        this.textBox31.Text = iniProperty19;
      if (iniProperty20 == null)
        return;
      this.textBox32.Text = iniProperty20;
    }

    public void CreateServerIni()
    {
      File.WriteAllText(Directory.GetCurrentDirectory() + "\\gameserver\\bin\\configs\\server.properties", "\r\n# Server id.\r\nserver.id =" + this.textBox1.Text + "\r\n\r\n# Краткое имя сервера (Должно быть в верхнем регистре)\r\nserver.short.name =" + this.textBox2.Text + "\r\n\r\n# ID канала.\r\nserver.channel.id =" + this.textBox3.Text + "\r\n\r\n# IP внешнего сервера для клиентских подключений\r\nserver.ip =" + this.textBox4.Text + " \r\n\r\n# Тип сервиса игрового сервера.\r\n# Варианты: DEV, KOR_REAL, NA_REAL, RUS_REAL, JPN_REAL\r\nserver.game.service.type =" + this.textBox5.Text + "\r\n\r\n# Тип ресурса игрового сервера.\r\n# Варианты: DEV, KR, EN, JP, CN, RU, FR, DE, ES\r\nserver.game.resource.type =" + this.textBox6.Text + "\r\n\r\n# Включить бонусы PC Cafe для игроков.\r\nserver.enable_pc_cafe_bonus =" + this.textBox7.Text + "\r\n\r\n# Предельные значения состояния занятости сервера.\r\nserver.busy_state_limit_inspection =" + this.textBox8.Text + "\r\n\r\nserver.busy_state_limit_smooth =" + this.textBox9.Text + "\r\n\r\nserver.busy_state_limit_busy =" + this.textBox10.Text + "\r\n\r\nserver.busy_state_limit_very_crowded =" + this.textBox11.Text + "\r\n\r\n\r\nserver.admin_only =" + this.textBox12.Text);
      int num = (int) MessageBox.Show("Updated server.properties");
    }

    public void CreateNetworkIni()
    {
      string contents = "\r\n# Хост подключения Rmi.\r\nnetwork.rmi.host =" + this.textBox13.Text + "\r\n\r\n# Порт подключения Rmi.\r\nnetwork.rmi.port =" + this.textBox14.Text + "\r\n\r\n# Пароль подключения Rmi.\r\nnetwork.rmi.password =" + this.textBox15.Text + "\r\n\r\n# Поддержка версии сервера\r\n# NA-EU: 4635\r\nnetwork.server.version =" + this.textBox16.Text + "\r\n\r\n# Поддержка еврапейского сервера.\r\nnetwork.encrypt.packets =" + this.textBox17.Text + "\r\n\r\n# Хост для привязки сервера.\r\n# По-умолчанию: 0.0.0.0\r\nnetwork.host =" + this.textBox18.Text + "\r\n\r\n# Порт для привязки к серверу.\r\n# По-умолчанию: 8888\r\nnetwork.port =" + this.textBox19.Text + "\r\n\r\n# Показать сообщения отладки.\r\n# По-умолчнию: false\r\nnetwork.debug =" + this.textBox20.Text + "\r\n\r\n# Пакетный режим выполнения.\r\n# DIRE#CT (Не рекомендуется). Входящие пакеты выполняются непосредственно после получения и дешифрования. Поскольку пакеты здесь реализованы ужасно, это не только увеличивает задержку, но и значительно снижает общую производительность.\r\n# OFFLOAD (Рекомендуется). выгружает выполнение в пул потоков. Хороший вариант с режимом POOLED IOExec. Увеличивает пропускную способность, но также может увеличить количество переключений контекста.\r\n# По-умолчанию: OFFLOAD\r\nnetwork.packet.exec.mode =" + this.textBox21.Text + "\r\n\r\n# Размер буфера приема.\r\n# По-умолчанию: 32768\r\nnetwork.recv.buffer.size =" + this.textBox22.Text + "\r\n\r\n# Размер буфера отправки.\r\n# По-умолчанию: 65536\r\nnetwork.send.buffer.size =" + this.textBox23.Text + "\r\n\r\n# Размер журнала ожидания сокета сети.\r\n# См. http://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/023/2333/2333s2.html\r\n# По-умолчанию: 50\r\nnetwork.server.socket.backlog =" + this.textBox24.Text + "\r\n\r\n#Параметры клиентских сокетов.\r\n# SO_SNDBUF - размер буфера отправки сокета. На большинстве систем это размер буфера ядра, поэтому будьте осторожны! См. RFC1323.\r\n# SO_RCVBUF - размер буфера приема сокета. На большинстве систем это размер буфера ядра, поэтому будьте осторожны! См. RFC1323.\r\n# TCP_NODELAY - алгоритм Nagle. Включение этого увеличивает пропускную способность, но также увеличивает задержку. См. RFC1122.\r\n# По-умолчанию: SO_SNDBUF(8192);SO_RCVBUF(8192);TCP_NODELAY(true)\r\nnetwork.client.socket.options =" + this.textBox25.Text + "\r\n\r\n# Параметры сокета сетевых потоков.\r\n# SO_REUSEADDR - если true, запрещает использование сокета до тех пор, пока все открытые сокеты не будут действительно закрыты. См. RFC793.\r\n# По-Умолчанию: SO_REUSEADDR(true);SO_RCVBUF(4096)\r\nnetwork.server.socket.options =" + this.textBox26.Text + "\r\n\r\n# Режим выполнения сетевого потока IO.\r\n# POOLED - все операции ввода-вывода выполняются в пуле выполнения специальных потоков ввода-вывода.\r\n# FIXED - Выполнение всех операций ввода-вывода распределено по фиксированному числу протекторов\r\n# По-умолчанию: POOLED\r\nnetwork.io.execution.mode =" + this.textBox27.Text + "\r\n\r\n# Количество потоков сети ввода-вывода.\r\n# По-умолчаниб: -1 (Количество процессоров)\r\nnetwork.io.execution.thread.num =" + this.textBox28.Text + "\r\n\r\n# Размер заголовка входящего пакета.\r\n# По-умолчанию: 3\r\nnetwork.income.packet.header.size =" + this.textBox29.Text + "\r\n\r\n# Максимальный размер входящего пакета.\r\n# По-умочланию: 16384\r\nnetwork.max.income.packet.size =" + this.textBox30.Text + "\r\n\r\n# Размер заголовка исходящего пакета.\r\n# По-умолчанию: 3\r\nnetwork.outcome.packet.header.size =" + this.textBox31.Text + "\r\n\r\n# Максимальный размер исходящего пакета.\r\n# Default: 16384\r\nnetwork.max.outcome.packet.size =" + this.textBox32.Text;
      File.WriteAllText(this._conf1, contents);
      File.WriteAllText(this._conf2, contents);
      int num = (int) MessageBox.Show("Обновлены оба network.properties!\n  (Game Server и Login Server)");
    }

    private void Button1_Click(object sender, EventArgs e)
    {
      this.CreateServerIni();
      this.CreateNetworkIni();
      this.Close();
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Networks));
      this.button1 = new Button();
      this.textBox1 = new TextBox();
      this.textBox2 = new TextBox();
      this.textBox3 = new TextBox();
      this.textBox4 = new TextBox();
      this.textBox5 = new TextBox();
      this.textBox6 = new TextBox();
      this.textBox7 = new TextBox();
      this.textBox8 = new TextBox();
      this.textBox9 = new TextBox();
      this.textBox10 = new TextBox();
      this.textBox11 = new TextBox();
      this.textBox12 = new TextBox();
      this.label1 = new Label();
      this.label2 = new Label();
      this.label3 = new Label();
      this.label4 = new Label();
      this.label5 = new Label();
      this.label6 = new Label();
      this.label7 = new Label();
      this.label8 = new Label();
      this.label9 = new Label();
      this.label10 = new Label();
      this.label11 = new Label();
      this.label12 = new Label();
      this.groupBox1 = new GroupBox();
      this.label13 = new Label();
      this.textBox13 = new TextBox();
      this.textBox14 = new TextBox();
      this.textBox15 = new TextBox();
      this.textBox16 = new TextBox();
      this.textBox17 = new TextBox();
      this.textBox18 = new TextBox();
      this.textBox19 = new TextBox();
      this.textBox20 = new TextBox();
      this.textBox21 = new TextBox();
      this.textBox22 = new TextBox();
      this.textBox23 = new TextBox();
      this.textBox24 = new TextBox();
      this.textBox25 = new TextBox();
      this.textBox26 = new TextBox();
      this.textBox27 = new TextBox();
      this.textBox28 = new TextBox();
      this.textBox29 = new TextBox();
      this.textBox30 = new TextBox();
      this.textBox31 = new TextBox();
      this.textBox32 = new TextBox();
      this.label14 = new Label();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label17 = new Label();
      this.label18 = new Label();
      this.label19 = new Label();
      this.label20 = new Label();
      this.label21 = new Label();
      this.label22 = new Label();
      this.label23 = new Label();
      this.label24 = new Label();
      this.label25 = new Label();
      this.label26 = new Label();
      this.label27 = new Label();
      this.label28 = new Label();
      this.label29 = new Label();
      this.label30 = new Label();
      this.label31 = new Label();
      this.label32 = new Label();
      this.label33 = new Label();
      this.groupBox2 = new GroupBox();
      this.groupBox1.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.SuspendLayout();
      this.button1.Location = new Point(11, 377);
      this.button1.Margin = new Padding(2);
      this.button1.Name = "button1";
      this.button1.Size = new Size(316, 133);
      this.button1.TabIndex = 0;
      this.button1.Text = "Save and Close";
      this.button1.UseVisualStyleBackColor = true;
      this.button1.Click += new EventHandler(this.Button1_Click);
      this.textBox1.Location = new Point(121, 23);
      this.textBox1.Margin = new Padding(2);
      this.textBox1.Name = "textBox1";
      this.textBox1.Size = new Size(184, 20);
      this.textBox1.TabIndex = 1;
      this.textBox2.Location = new Point(121, 48);
      this.textBox2.Margin = new Padding(2);
      this.textBox2.Name = "textBox2";
      this.textBox2.Size = new Size(184, 20);
      this.textBox2.TabIndex = 2;
      this.textBox3.Location = new Point(121, 73);
      this.textBox3.Margin = new Padding(2);
      this.textBox3.Name = "textBox3";
      this.textBox3.Size = new Size(184, 20);
      this.textBox3.TabIndex = 3;
      this.textBox4.Location = new Point(121, 97);
      this.textBox4.Margin = new Padding(2);
      this.textBox4.Name = "textBox4";
      this.textBox4.Size = new Size(184, 20);
      this.textBox4.TabIndex = 4;
      this.textBox5.Location = new Point(121, 122);
      this.textBox5.Margin = new Padding(2);
      this.textBox5.Name = "textBox5";
      this.textBox5.Size = new Size(184, 20);
      this.textBox5.TabIndex = 5;
      this.textBox6.Location = new Point(121, 147);
      this.textBox6.Margin = new Padding(2);
      this.textBox6.Name = "textBox6";
      this.textBox6.Size = new Size(184, 20);
      this.textBox6.TabIndex = 6;
      this.textBox7.Location = new Point(121, 172);
      this.textBox7.Margin = new Padding(2);
      this.textBox7.Name = "textBox7";
      this.textBox7.Size = new Size(184, 20);
      this.textBox7.TabIndex = 7;
      this.textBox8.Location = new Point(121, 246);
      this.textBox8.Margin = new Padding(2);
      this.textBox8.Name = "textBox8";
      this.textBox8.Size = new Size(184, 20);
      this.textBox8.TabIndex = 9;
      this.textBox9.Location = new Point(121, 271);
      this.textBox9.Margin = new Padding(2);
      this.textBox9.Name = "textBox9";
      this.textBox9.Size = new Size(184, 20);
      this.textBox9.TabIndex = 10;
      this.textBox10.Location = new Point(121, 296);
      this.textBox10.Margin = new Padding(2);
      this.textBox10.Name = "textBox10";
      this.textBox10.Size = new Size(184, 20);
      this.textBox10.TabIndex = 11;
      this.textBox11.Location = new Point(121, 320);
      this.textBox11.Margin = new Padding(2);
      this.textBox11.Name = "textBox11";
      this.textBox11.Size = new Size(184, 20);
      this.textBox11.TabIndex = 12;
      this.textBox12.Location = new Point(121, 195);
      this.textBox12.Margin = new Padding(2);
      this.textBox12.Name = "textBox12";
      this.textBox12.Size = new Size(184, 20);
      this.textBox12.TabIndex = 8;
      this.label1.AutoSize = true;
      this.label1.Location = new Point(14, 25);
      this.label1.Margin = new Padding(2, 0, 2, 0);
      this.label1.Name = "label1";
      this.label1.Size = new Size(49, 13);
      this.label1.TabIndex = 13;
      this.label1.Text = "Server id";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(14, 50);
      this.label2.Margin = new Padding(2, 0, 2, 0);
      this.label2.Name = "label2";
      this.label2.Size = new Size(97, 13);
      this.label2.TabIndex = 14;
      this.label2.Text = "Short Server Name";
      this.label3.AutoSize = true;
      this.label3.Location = new Point(14, 75);
      this.label3.Margin = new Padding(2, 0, 2, 0);
      this.label3.Name = "label3";
      this.label3.Size = new Size(57, 13);
      this.label3.TabIndex = 15;
      this.label3.Text = "Channel id";
      this.label4.AutoSize = true;
      this.label4.Location = new Point(14, 99);
      this.label4.Margin = new Padding(2, 0, 2, 0);
      this.label4.Name = "label4";
      this.label4.Size = new Size(51, 13);
      this.label4.TabIndex = 16;
      this.label4.Text = "Server IP";
      this.label5.AutoSize = true;
      this.label5.Location = new Point(14, 124);
      this.label5.Margin = new Padding(2, 0, 2, 0);
      this.label5.Name = "label5";
      this.label5.Size = new Size(65, 13);
      this.label5.TabIndex = 17;
      this.label5.Text = "Server Type";
      this.label6.AutoSize = true;
      this.label6.Location = new Point(14, 149);
      this.label6.Margin = new Padding(2, 0, 2, 0);
      this.label6.Name = "label6";
      this.label6.Size = new Size(55, 13);
      this.label6.TabIndex = 18;
      this.label6.Text = "Language";
      this.label7.AutoSize = true;
      this.label7.Location = new Point(14, 174);
      this.label7.Margin = new Padding(2, 0, 2, 0);
      this.label7.Name = "label7";
      this.label7.Size = new Size(90, 13);
      this.label7.TabIndex = 19;
      this.label7.Text = "PC Cafe Bonuses";
      this.label8.AutoSize = true;
      this.label8.Location = new Point(14, 248);
      this.label8.Margin = new Padding(2, 0, 2, 0);
      this.label8.Name = "label8";
      this.label8.Size = new Size(78, 13);
      this.label8.TabIndex = 20;
      this.label8.Text = "limit_inspection";
      this.label9.AutoSize = true;
      this.label9.Location = new Point(14, 273);
      this.label9.Margin = new Padding(2, 0, 2, 0);
      this.label9.Name = "label9";
      this.label9.Size = new Size(64, 13);
      this.label9.TabIndex = 21;
      this.label9.Text = "limit_smooth";
      this.label10.AutoSize = true;
      this.label10.Location = new Point(14, 298);
      this.label10.Margin = new Padding(2, 0, 2, 0);
      this.label10.Name = "label10";
      this.label10.Size = new Size(52, 13);
      this.label10.TabIndex = 22;
      this.label10.Text = "limit_busy";
      this.label11.AutoSize = true;
      this.label11.Location = new Point(14, 322);
      this.label11.Margin = new Padding(2, 0, 2, 0);
      this.label11.Name = "label11";
      this.label11.Size = new Size(97, 13);
      this.label11.TabIndex = 23;
      this.label11.Text = "limit_very_crowded";
      this.label12.AutoSize = true;
      this.label12.Location = new Point(14, 197);
      this.label12.Margin = new Padding(2, 0, 2, 0);
      this.label12.Name = "label12";
      this.label12.Size = new Size(60, 13);
      this.label12.TabIndex = 24;
      this.label12.Text = "Admin Only";
      this.groupBox1.Controls.Add((Control) this.label13);
      this.groupBox1.Controls.Add((Control) this.label1);
      this.groupBox1.Controls.Add((Control) this.label12);
      this.groupBox1.Controls.Add((Control) this.textBox1);
      this.groupBox1.Controls.Add((Control) this.label11);
      this.groupBox1.Controls.Add((Control) this.textBox2);
      this.groupBox1.Controls.Add((Control) this.label10);
      this.groupBox1.Controls.Add((Control) this.textBox3);
      this.groupBox1.Controls.Add((Control) this.label9);
      this.groupBox1.Controls.Add((Control) this.textBox4);
      this.groupBox1.Controls.Add((Control) this.label8);
      this.groupBox1.Controls.Add((Control) this.textBox5);
      this.groupBox1.Controls.Add((Control) this.label7);
      this.groupBox1.Controls.Add((Control) this.textBox6);
      this.groupBox1.Controls.Add((Control) this.label6);
      this.groupBox1.Controls.Add((Control) this.textBox7);
      this.groupBox1.Controls.Add((Control) this.label5);
      this.groupBox1.Controls.Add((Control) this.textBox8);
      this.groupBox1.Controls.Add((Control) this.label4);
      this.groupBox1.Controls.Add((Control) this.textBox9);
      this.groupBox1.Controls.Add((Control) this.label3);
      this.groupBox1.Controls.Add((Control) this.textBox10);
      this.groupBox1.Controls.Add((Control) this.label2);
      this.groupBox1.Controls.Add((Control) this.textBox11);
      this.groupBox1.Controls.Add((Control) this.textBox12);
      this.groupBox1.Location = new Point(11, 11);
      this.groupBox1.Margin = new Padding(2);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Padding = new Padding(2);
      this.groupBox1.Size = new Size(316, 350);
      this.groupBox1.TabIndex = 25;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Server Settings";
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Microsoft Sans Serif", 8f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label13.Location = new Point(34, 224);
      this.label13.Margin = new Padding(2, 0, 2, 0);
      this.label13.Name = "label13";
      this.label13.Size = new Size(104, 13);
      this.label13.TabIndex = 26;
      this.label13.Text = "Busy State Limits";
      this.textBox13.Location = new Point(196, 13);
      this.textBox13.Name = "textBox13";
      this.textBox13.Size = new Size(332, 20);
      this.textBox13.TabIndex = 26;
      this.textBox14.Location = new Point(196, 35);
      this.textBox14.Name = "textBox14";
      this.textBox14.Size = new Size(332, 20);
      this.textBox14.TabIndex = 27;
      this.textBox15.Location = new Point(196, 57);
      this.textBox15.Name = "textBox15";
      this.textBox15.Size = new Size(332, 20);
      this.textBox15.TabIndex = 28;
      this.textBox16.Location = new Point(196, 79);
      this.textBox16.Name = "textBox16";
      this.textBox16.Size = new Size(332, 20);
      this.textBox16.TabIndex = 29;
      this.textBox17.Location = new Point(196, 101);
      this.textBox17.Name = "textBox17";
      this.textBox17.Size = new Size(332, 20);
      this.textBox17.TabIndex = 30;
      this.textBox18.Location = new Point(196, 123);
      this.textBox18.Name = "textBox18";
      this.textBox18.Size = new Size(332, 20);
      this.textBox18.TabIndex = 31;
      this.textBox19.Location = new Point(196, 145);
      this.textBox19.Name = "textBox19";
      this.textBox19.Size = new Size(332, 20);
      this.textBox19.TabIndex = 32;
      this.textBox20.Location = new Point(196, 167);
      this.textBox20.Name = "textBox20";
      this.textBox20.Size = new Size(332, 20);
      this.textBox20.TabIndex = 33;
      this.textBox21.Location = new Point(196, 189);
      this.textBox21.Name = "textBox21";
      this.textBox21.Size = new Size(332, 20);
      this.textBox21.TabIndex = 34;
      this.textBox22.Location = new Point(196, 211);
      this.textBox22.Name = "textBox22";
      this.textBox22.Size = new Size(332, 20);
      this.textBox22.TabIndex = 35;
      this.textBox23.Location = new Point(196, 233);
      this.textBox23.Name = "textBox23";
      this.textBox23.Size = new Size(332, 20);
      this.textBox23.TabIndex = 36;
      this.textBox24.Location = new Point(196, (int) byte.MaxValue);
      this.textBox24.Name = "textBox24";
      this.textBox24.Size = new Size(332, 20);
      this.textBox24.TabIndex = 37;
      this.textBox25.Location = new Point(196, 277);
      this.textBox25.Name = "textBox25";
      this.textBox25.Size = new Size(332, 20);
      this.textBox25.TabIndex = 38;
      this.textBox26.Location = new Point(196, 299);
      this.textBox26.Name = "textBox26";
      this.textBox26.Size = new Size(332, 20);
      this.textBox26.TabIndex = 39;
      this.textBox27.Location = new Point(196, 321);
      this.textBox27.Name = "textBox27";
      this.textBox27.Size = new Size(332, 20);
      this.textBox27.TabIndex = 40;
      this.textBox28.Location = new Point(196, 343);
      this.textBox28.Name = "textBox28";
      this.textBox28.Size = new Size(332, 20);
      this.textBox28.TabIndex = 41;
      this.textBox29.Location = new Point(196, 365);
      this.textBox29.Name = "textBox29";
      this.textBox29.Size = new Size(332, 20);
      this.textBox29.TabIndex = 42;
      this.textBox30.Location = new Point(196, 387);
      this.textBox30.Name = "textBox30";
      this.textBox30.Size = new Size(332, 20);
      this.textBox30.TabIndex = 43;
      this.textBox31.Location = new Point(196, 409);
      this.textBox31.Name = "textBox31";
      this.textBox31.Size = new Size(332, 20);
      this.textBox31.TabIndex = 44;
      this.textBox32.Location = new Point(196, 431);
      this.textBox32.Name = "textBox32";
      this.textBox32.Size = new Size(332, 20);
      this.textBox32.TabIndex = 45;
      this.label14.AutoSize = true;
      this.label14.Location = new Point(18, 16);
      this.label14.Name = "label14";
      this.label14.Size = new Size(52, 13);
      this.label14.TabIndex = 46;
      this.label14.Text = "RMI Хост";
      this.label15.AutoSize = true;
      this.label15.Location = new Point(18, 38);
      this.label15.Name = "label15";
      this.label15.Size = new Size(49, 13);
      this.label15.TabIndex = 47;
      this.label15.Text = "RMI Порт";
      this.label16.AutoSize = true;
      this.label16.Location = new Point(18, 60);
      this.label16.Name = "label16";
      this.label16.Size = new Size(76, 13);
      this.label16.TabIndex = 48;
      this.label16.Text = "RMI Пароль";
      this.label17.AutoSize = true;
      this.label17.Location = new Point(18, 82);
      this.label17.Name = "label17";
      this.label17.Size = new Size(76, 13);
      this.label17.TabIndex = 49;
      this.label17.Text = "Версия сервера";
      this.label18.AutoSize = true;
      this.label18.Location = new Point(18, 104);
      this.label18.Name = "label18";
      this.label18.Size = new Size(62, 13);
      this.label18.TabIndex = 50;
      this.label18.Text = "Поддержка ЕвроКлиента";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(18, 126);
      this.label19.Name = "label19";
      this.label19.Size = new Size(42, 13);
      this.label19.TabIndex = 51;
      this.label19.Text = "IP хоста";
      this.label20.AutoSize = true;
      this.label20.Location = new Point(18, 148);
      this.label20.Name = "label20";
      this.label20.Size = new Size(51, 13);
      this.label20.TabIndex = 52;
      this.label20.Text = "Порт хоста";
      this.label21.AutoSize = true;
      this.label21.Location = new Point(18, 170);
      this.label21.Name = "label21";
      this.label21.Size = new Size(120, 13);
      this.label21.TabIndex = 53;
      this.label21.Text = "Показать сообщения отладки";
      this.label22.AutoSize = true;
      this.label22.Location = new Point(18, 192);
      this.label22.Name = "label22";
      this.label22.Size = new Size(121, 13);
      this.label22.TabIndex = 54;
      this.label22.Text = "Режим выполнения пакетов";
      this.label23.AutoSize = true;
      this.label23.Location = new Point(18, 214);
      this.label23.Name = "label23";
      this.label23.Size = new Size(101, 13);
      this.label23.TabIndex = 55;
      this.label23.Text = "Размер буфера получения";
      this.label24.AutoSize = true;
      this.label24.Location = new Point(18, 236);
      this.label24.Name = "label24";
      this.label24.Size = new Size(86, 13);
      this.label24.TabIndex = 56;
      this.label24.Text = "Размер буфера отправки";
      this.label25.AutoSize = true;
      this.label25.Location = new Point(18, 258);
      this.label25.Name = "label25";
      this.label25.Size = new Size(160, 13);
      this.label25.TabIndex = 57;
      this.label25.Text = "Журнал ожидания сетевого потока";
      this.label26.AutoSize = true;
      this.label26.Location = new Point(18, 280);
      this.label26.Name = "label26";
      this.label26.Size = new Size(105, 13);
      this.label26.TabIndex = 58;
      this.label26.Text = "Параметры клиентских сокетов";
      this.label27.AutoSize = true;
      this.label27.Location = new Point(18, 302);
      this.label27.Name = "label27";
      this.label27.Size = new Size(153, 13);
      this.label27.TabIndex = 59;
      this.label27.Text = "Параметры сетевого сокета";
      this.label28.AutoSize = true;
      this.label28.Location = new Point(18, 324);
      this.label28.Name = "label28";
      this.label28.Size = new Size(172, 13);
      this.label28.TabIndex = 60;
      this.label28.Text = "Режим выполнения сетевого потока ввода-вывода";
      this.label29.AutoSize = true;
      this.label29.Location = new Point(18, 346);
      this.label29.Name = "label29";
      this.label29.Size = new Size(151, 13);
      this.label29.TabIndex = 61;
      this.label29.Text = "Количество потоков сети ввода-вывода";
      this.label30.AutoSize = true;
      this.label30.Location = new Point(18, 368);
      this.label30.Name = "label30";
      this.label30.Size = new Size(135, 13);
      this.label30.TabIndex = 62;
      this.label30.Text = "Размер заголовка входящего пакета";
      this.label31.AutoSize = true;
      this.label31.Location = new Point(18, 390);
      this.label31.Name = "label31";
      this.label31.Size = new Size(121, 13);
      this.label31.TabIndex = 63;
      this.label31.Text = "Максимальный размер пакета";
      this.label32.AutoSize = true;
      this.label32.Location = new Point(18, 412);
      this.label32.Name = "label32";
      this.label32.Size = new Size(143, 13);
      this.label32.TabIndex = 64;
      this.label32.Text = "Размер заголовка исходящего пакета";
      this.label33.AutoSize = true;
      this.label33.Location = new Point(18, 434);
      this.label33.Name = "label33";
      this.label33.Size = new Size(128, 13);
      this.label33.TabIndex = 65;
      this.label33.Text = "Максимальный размер конечного пакета";
      this.groupBox2.Controls.Add((Control) this.label14);
      this.groupBox2.Controls.Add((Control) this.label33);
      this.groupBox2.Controls.Add((Control) this.textBox13);
      this.groupBox2.Controls.Add((Control) this.label32);
      this.groupBox2.Controls.Add((Control) this.textBox14);
      this.groupBox2.Controls.Add((Control) this.label31);
      this.groupBox2.Controls.Add((Control) this.textBox15);
      this.groupBox2.Controls.Add((Control) this.label30);
      this.groupBox2.Controls.Add((Control) this.textBox16);
      this.groupBox2.Controls.Add((Control) this.label29);
      this.groupBox2.Controls.Add((Control) this.textBox17);
      this.groupBox2.Controls.Add((Control) this.label28);
      this.groupBox2.Controls.Add((Control) this.textBox22);
      this.groupBox2.Controls.Add((Control) this.label27);
      this.groupBox2.Controls.Add((Control) this.textBox21);
      this.groupBox2.Controls.Add((Control) this.label26);
      this.groupBox2.Controls.Add((Control) this.textBox20);
      this.groupBox2.Controls.Add((Control) this.label25);
      this.groupBox2.Controls.Add((Control) this.textBox19);
      this.groupBox2.Controls.Add((Control) this.label24);
      this.groupBox2.Controls.Add((Control) this.textBox18);
      this.groupBox2.Controls.Add((Control) this.label23);
      this.groupBox2.Controls.Add((Control) this.textBox27);
      this.groupBox2.Controls.Add((Control) this.label22);
      this.groupBox2.Controls.Add((Control) this.textBox26);
      this.groupBox2.Controls.Add((Control) this.label21);
      this.groupBox2.Controls.Add((Control) this.textBox25);
      this.groupBox2.Controls.Add((Control) this.label20);
      this.groupBox2.Controls.Add((Control) this.textBox24);
      this.groupBox2.Controls.Add((Control) this.label19);
      this.groupBox2.Controls.Add((Control) this.textBox23);
      this.groupBox2.Controls.Add((Control) this.label18);
      this.groupBox2.Controls.Add((Control) this.textBox32);
      this.groupBox2.Controls.Add((Control) this.label17);
      this.groupBox2.Controls.Add((Control) this.textBox31);
      this.groupBox2.Controls.Add((Control) this.label16);
      this.groupBox2.Controls.Add((Control) this.textBox30);
      this.groupBox2.Controls.Add((Control) this.label15);
      this.groupBox2.Controls.Add((Control) this.textBox29);
      this.groupBox2.Controls.Add((Control) this.textBox28);
      this.groupBox2.Location = new Point(344, 12);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(538, 498);
      this.groupBox2.TabIndex = 66;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Сетевые настройки";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(897, 521);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.groupBox1);
      this.Controls.Add((Control) this.button1);
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.Margin = new Padding(2);
      this.Name = nameof (Networks);
      this.Text = nameof (Networks);
      this.groupBox1.ResumeLayout(false);
      this.groupBox1.PerformLayout();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
